-- Seed initial X accounts, news sources, and Hormuz keywords.
-- Safe to re-run; uses on conflict do nothing.

insert into x_accounts (handle, display_name, role, importance, category, notes)
values
  ('POTUS',          'POTUS',                    'US President',                10, 'politics',   'Official account'),
  ('WhiteHouse',     'The White House',          'US executive',                 9, 'politics',   null),
  ('StateDept',      'US State Department',      'US diplomacy',                 9, 'politics',   null),
  ('SecDef',         'US Secretary of Defense',  'US defense',                  10, 'war',        null),
  ('DeptofDefense',  'US DoD',                   'US defense',                   9, 'war',        null),
  ('CENTCOM',        'US Central Command',       'US military, ME AOR',         10, 'war',        'Middle East AOR'),
  ('IDF',            'Israel Defense Forces',    'IDF',                          9, 'war',        null),
  ('IsraeliPM',      'Israeli PM',               'Israeli leadership',           9, 'politics',   null),
  ('khamenei_ir',    'Ali Khamenei',             'Iran supreme leader',          9, 'politics',   null),
  ('Iran_GOV',       'Iran Government',          'Iranian government',           7, 'politics',   null),
  ('IRGC_QF',        'IRGC related',             'IRGC commentary',              6, 'war',        'Unofficial / commentary'),
  ('SecBlinken',     'US Secretary of State',    'US diplomacy',                 7, 'politics',   null),
  ('UN',             'United Nations',           'UN',                           7, 'politics',   null),
  ('IAEAorg',        'IAEA',                     'Nuclear watchdog',             8, 'war',        null),
  ('Reuters',        'Reuters',                  'Newswire',                     8, 'politics',   null),
  ('AP',             'Associated Press',         'Newswire',                     8, 'politics',   null),
  ('BBCBreaking',    'BBC Breaking News',        'Breaking news',                8, 'politics',   null),
  ('AJEnglish',      'Al Jazeera English',       'News',                         7, 'politics',   null),
  ('TheCradleMedia', 'The Cradle',               'West Asia analysis',           5, 'geopolitics',null),
  ('AuroraIntel',    'Aurora Intel',             'OSINT',                        7, 'war',        null),
  ('IntelCrab',      'IntelCrab',                'OSINT',                        6, 'war',        null),
  ('sentdefender',   'OSINTdefender',            'OSINT',                        6, 'war',        null),
  ('JulianRoepcke',  'Julian Roepcke',           'Conflict analyst',             6, 'war',        null),
  ('TankerTrackers', 'TankerTrackers.com',       'Maritime / oil flows',         9, 'geopolitics','Strait of Hormuz signal'),
  ('Reuters_Energy', 'Reuters Energy',           'Oil / gas markets',            7, 'geopolitics','Hormuz signal')
on conflict (handle) do nothing;

insert into news_sources (id, name, rss_url, homepage, keywords)
values
  ('reuters-world',  'Reuters World',
     'https://feeds.reuters.com/Reuters/worldNews',
     'https://www.reuters.com/world/',
     '["politics","war","conflict","middle east","iran","israel","russia","ukraine","china","taiwan","hormuz","strait of hormuz","tanker","oil"]'::jsonb),
  ('reuters-mideast','Reuters Middle East',
     'https://www.reutersagency.com/feed/?best-regions=middle-east&post_type=best',
     'https://www.reuters.com/world/middle-east/',
     '["iran","israel","gaza","lebanon","yemen","houthi","hormuz","saudi","iraq","syria","tanker","oil"]'::jsonb),
  ('ap-top',         'AP Top News',
     'https://rsshub.app/apnews/topics/apf-topnews',
     'https://apnews.com/',
     '["politics","war","conflict","middle east","iran","israel","russia","ukraine","hormuz"]'::jsonb),
  ('bbc-world',      'BBC World',
     'https://feeds.bbci.co.uk/news/world/rss.xml',
     'https://www.bbc.com/news/world',
     '["politics","war","conflict","iran","israel","russia","ukraine","hormuz"]'::jsonb),
  ('aljazeera',      'Al Jazeera',
     'https://www.aljazeera.com/xml/rss/all.xml',
     'https://www.aljazeera.com/',
     '["politics","war","middle east","iran","israel","gaza","hormuz","yemen","houthi"]'::jsonb),
  ('bloomberg-poli', 'Bloomberg Politics',
     'https://feeds.bloomberg.com/politics/news.rss',
     'https://www.bloomberg.com/politics',
     '["politics","election","war","iran","russia","china"]'::jsonb),
  ('guardian-world', 'The Guardian World',
     'https://www.theguardian.com/world/rss',
     'https://www.theguardian.com/world',
     '["politics","war","middle east","iran","israel","russia","ukraine","hormuz"]'::jsonb),
  ('ft-world',       'Financial Times World',
     'https://www.ft.com/world?format=rss',
     'https://www.ft.com/world',
     '["politics","war","iran","russia","china","oil","hormuz"]'::jsonb),
  ('nyt-world',      'NYTimes World',
     'https://rss.nytimes.com/services/xml/rss/nyt/World.xml',
     'https://www.nytimes.com/section/world',
     '["politics","war","middle east","iran","israel","russia","ukraine","hormuz"]'::jsonb),
  ('cnn-world',      'CNN World',
     'https://rss.cnn.com/rss/edition_world.rss',
     'http://edition.cnn.com/world',
     '["politics","war","iran","israel","russia","ukraine","hormuz"]'::jsonb)
on conflict (id) do nothing;
